export const LOGIN_DETAILS_SUCCESS = "LOGIN_DETAILS_SUCCESS";
export const LOGIN_DETAILS_FAILURE = "LOGIN_DETAILS_FAILURE";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const SET_LOGIN_VALUE = "SET_LOGIN_VALUE";
